# name: Create a release when a new commit on master with package.json version changes

# on:
#   push:
#     branches:
#       - master

# jobs:
#   create-release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Create Release
#         uses: Makepad-fr/auto-release-on-version-bump-action@master
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}